### ISSUE TITLE
v0.0.1

### ISSUE THREAD

**Issue by iam-yan** [iam-yan/clibook#1]
- [x] Initial checking
    - [x] Check if there is saved study book
    - [x] Generate study book from the saved json
    - [x] Check if there are any words in the book's backlog
---
- [x] Ask for the next step
    - [x] Ask for input if there is no wordbook, or there are no words left in the backlog
    - [x] Ask user to determine what's the next: Input or Study?
---
- [x] Parse the input
    - [x] Convert string of input to wordbook
    - [x] Merge with the existing wordbook
    - [x] Convert into json
    - [x] Store in a file
    - [x] Report result, for example: `23 new words from 2 sentences, now 58 words of 12 sentences`
---
- [x] Study
    - [x] Pick random word which has a level larger than 0, no repeat until walking through each word
    - [x] Print kanji or hiragana
    - [x] Get users' input of its hiragana and kanji
    - [x] Tell the result, with all the knowledge of this word and it's sentence printed
    - [x] Wrong -> level up
    - [x] Correct -> level down
